nodeLinker: node-modules

npmPublishRegistry: "https://professorbob-ai-291845142233.d.codeartifact.eu-west-3.amazonaws.com/npm/npm.registery.profressorbob/"

npmRegistryServer: "https://professorbob-ai-291845142233.d.codeartifact.eu-west-3.amazonaws.com/npm/npm.registery.profressorbob/"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
